### ISSUE TITLE
Write a plugin for PostHTML

### ISSUE THREAD

**Issue by outpunk** [outpunk/postcss-modules#11]
https://github.com/posthtml/posthtml/issues/85

**Comment by voischev** [comment]
:+1:

**Comment by maltsev** [comment]
@outpunk are you already working on the plugin? I was thinking to develop a similar plugin, but then I saw this issue.

**Comment by outpunk** [comment]
@maltsev  Going to start next week.

**Comment by maltsev** [comment]
@outpunk ok. Then I'd not develop my own.

**Comment by maltsev** [comment]
@outpunk do you need help with that?

**Comment by outpunk** [comment]
I'm going to rewrite `postcss-modules` completely first in order to fix some bugs and provide full CSS Modules support. Next week, I think. Sorry for making you waiting.

**Comment by maltsev** [comment]
Okay, no problem.

**Comment by maltsev** [comment]
Done: [posthtml-css-modules](https://www.npmjs.com/package/posthtml-css-modules)

**Comment by outpunk** [comment]
@maltsev Great, thank you!
