### ISSUE TITLE
CSS import are overwritten

### ISSUE THREAD

**Issue by ifraixedes** [outpunk/postcss-modules#15]
Making some experiment I've found that `getJSON` is called only with the the last CSS imported file.

I created a CSS file with two included files, e.g.

```css
@import './styles/first.css'
@import './styles/second.css'
```

And then I found that `getJSON` is only called with the mapped names corresponding to `second.css`. I tried only with the first import (`first.css`) and I got the mapping for it, but when I added the `second.css` then I got the mapping for the `second.css` meanwhile I expected to find all of them.

I also realised that `filename` received as first parameter in `getJSON` is always `undefined` at least for this specific scenario.

**Comment by outpunk** [comment]
I'm going to rewrite the implementation and fix the problem by the way. Not sure about this week, but hope I can do this next week.

**Comment by ifraixedes** [comment]
@outpunk it's very good dude.

Your dedication is pretty awesome :muscle: 

Thanks.

**Comment by outpunk** [comment]
Started working on this yesterday, keep tuned!

**Comment by outpunk** [comment]
@ifraixedes @simonsmith Fixed, the new version is published

**Comment by simonsmith** [comment]
Awesome, thanks for that!
