### ISSUE TITLE
Version for Webpack?

### ISSUE THREAD

**Issue by wzup** [outpunk/postcss-modules#20]
Do you have it as Webpack `-loader`? If you do, how to use it for both server side and client side rendering in one project?

**Comment by outpunk** [comment]
You should use [css-loader](https://github.com/webpack/css-loader). If you want to use CSS Modules on the both sides, just use postcss-modules as in [the example](https://github.com/outpunk/postcss-modules-example) along with css-loader. Also, make sure that you use the same configuration rules for the classes tranformation.
