### ISSUE TITLE
how to work in gulp

### ISSUE THREAD

**Issue by zhouwenbin** [outpunk/postcss-modules#8]

**Comment by TrySound** [comment]
@zhouwenbin https://github.com/postcss/gulp-postcss

**Comment by zhouwenbin** [comment]
i had include it.but the usage didn't work

**Comment by TrySound** [comment]
@zhouwenbin Any error, input, output? Please report all information if you want to get good answer.

**Comment by zhouwenbin** [comment]
require is not function...

**Comment by TrySound** [comment]
@zhouwenbin Code?

**Comment by zhouwenbin** [comment]
sorry, i have leave the computer.i use the usage code and pause in a pipe()

**Comment by zhouwenbin** [comment]
thanks,i will try tomorrow.

**Comment by outpunk** [comment]
@zhouwenbin just published the updated version, please check.

**Comment by zhouwenbin** [comment]
https://github.com/outpunk/postcss-modules/pull/10
