### ISSUE TITLE
es2015 export

### ISSUE THREAD

**Issue by TrySound** [outpunk/postcss-modules#9]
babel6 uses exports default module value in property and this plugin can't work regular in node without es2015 modules support
```js
require('postcss-moduels').default()
```
You can fix it by using regular `module.exports` in src/index.js

**Comment by TrySound** [comment]
Seems like this is related https://github.com/outpunk/postcss-modules/issues/8

**Comment by vlkosinov** [comment]
@outpunk @TrySound in this case preferable to use this plugin http://babeljs.io/docs/plugins/transform-es2015-modules-commonjs

**Comment by outpunk** [comment]
Thanks!
